# Generated by Django 5.2.3 on 2025-07-24 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productmodel_color_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-update', '-timestamp']},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('BR', 'BORRADOR'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
